# Generated by Django 2.2.4 on 2019-10-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0006_delete_locationbikecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Location')),
            ],
        ),
    ]
