# Generated by Django 2.2.4 on 2019-10-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationbikecount',
            options={'ordering': ('datetime',)},
        ),
    ]
