# Generated by Django 2.2.4 on 2019-10-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191020_1118'),
        ('reports', '0002_auto_20191018_1050'),
    ]

    operations = [
    ]
