# Generated by Django 2.2.4 on 2019-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikehires',
            options={'ordering': ('date_hired',)},
        ),
        migrations.AddField(
            model_name='location',
            name='initial_bike_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
