# Generated by Django 2.2.4 on 2019-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20191014_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='initial_bike_count',
            field=models.IntegerField(default=0),
        ),
    ]
