# Generated by Django 2.2.4 on 2019-10-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_locationbikecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikehires',
            name='date_hired',
            field=models.DateTimeField(),
        ),
    ]
