# Generated by Django 2.2.4 on 2019-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='last_hired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
