# Generated by Django 2.2.4 on 2019-10-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_bikes_last_hired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikes',
            options={'ordering': ('last_hired',)},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_hire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.BikeHires'),
        ),
    ]
