# Generated by Django 2.2.4 on 2019-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_auto_20191030_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='charges',
            field=models.FloatField(default=10),
        ),
    ]
