# Generated by Django 2.2.4 on 2019-11-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_auto_20191102_2213'),
        ('bikes', '0011_auto_20191101_1529'),
    ]

    operations = [
    ]
